import keyMirror from 'react/lib/keyMirror';

export default {
    ADD_LEAVE_TYPE : 'ADD_LEAVE_TYPE',
    GET_DATA_TO_EDIT : 'GET_DATA_TO_EDIT',
    UPDATE_EMPLOYEE_TYPE : 'UPDATE_EMPLOYEE_TYPE',
    GET_ALL_LEAVE_TYPE : 'GET_ALL_LEAVE_TYPE',
    REMOVE_TYPE_LEAVE : 'REMOVE_TYPE_LEAVE',
    ASSIGN_LEAVE : 'ASSIGN_LEAVE',
    GET_ALL_ENTITLE : 'GET_ALL_ENTITLE',
    GET_ENTITLE : 'GET_ENTITLE',
    ADD_LEAVE_ENTITLEMENT : 'ADD_LEAVE_ENTITLEMENT',
    GET_ALL_PERIOD:'GET_ALL_PERIOD',
    REMOVE_LEAVE_ENTITLE : 'REMOVE_LEAVE_ENTITLE',
    GET_LEAVE_TYPE : 'GET_LEAVE_TYPE',
    ACTION_LEAVE: 'ACTION_LEAVE',
    GET_LIST_ASSIGN : 'GET_LIST_ASSIGN',
    SCHEDULER_ASSIGN:'SCHEDULER_ASSIGN',
    DELETE_CALENDAR_ASSIGN:'DELETE_CALENDAR_ASSIGN',
    GET_LIST_ASSIGN_USER:'GET_LIST_ASSIGN_USER',
    CHECK_ENTITLE : 'CHECK_ENTITLE',
    CHECK_ENTITLE_LEAVE :'CHECK_ENTITLE_LEAVE',
    GET_PERIODS:'GET_PERIODS',
    GET_LEAVE_EM:'GET_LEAVE_EM',
    GET_ENTITLE_BY_ID:'GET_ENTITLE_BY_ID'
}
