export default[
	{value:1,name:'Afghan'},
	{value:2,name:'Albanian'},
	{value:3,name:'Algerian'},
	{value:4,name:'American'},
	{value:5,name:'Andorran'},
	{value:6,name:'Angolan'},
	{value:7,name:'Antiguans'},
	{value:8,name:'Argentinean'},
	{value:9,name:'Armenian'},
	{value:10,name:'Australian'},
	{value:11,name:'Austrian'},
	{value:12,name:'Azerbaijani'},
	{value:13,name:'Bahamian'},
	{value:14,name:'Bahraini'},
	{value:15,name:'Bangladeshi'},
	{value:16,name:'Barbadian'},
	{value:17,name:'Barbudans'},
	{value:18,name:'Batswana'},
	{value:19,name:'Belarusian'},
	{value:20,name:'Belgian'},
	{value:21,name:'Belizean'},
	{value:22,name:'Beninese'},
	{value:23,name:'Bhutanese'},
	{value:24,name:'Bolivian'},
	{value:25,name:'Bosnian'},
	{value:26,name:'Brazilian'},
	{value:27,name:'British'},
	{value:28,name:'Bruneian'},
	{value:29,name:'Bulgarian'},
	{value:30,name:'Burkinabe'},
	{value:31,name:'Burmese'},
	{value:32,name:'Burundian'},
	{value:33,name:'Cambodian'},
	{value:34,name:'Cameroonian'},
	{value:35,name:'Canadian'},
	{value:36,name:'Cape Verdean'},
	{value:37,name:'Central African'},
	{value:38,name:'Chadian'},
	{value:39,name:'Chilean'},
	{value:40,name:'Chinese'},
	{value:41,name:'Colombian'},
	{value:42,name:'Comoran'},
	{value:43,name:'Congolese'},
	{value:44,name:'Costa Rican'},
	{value:45,name:'Croatian'},
	{value:46,name:'Cuban'},
	{value:47,name:'Cypriot'},
	{value:48,name:'Czech'},
	{value:49,name:'Danish'},
	{value:50,name:'Djibouti'},
	{value:51,name:'Dominican'},
	{value:52,name:'Dutch'},
	{value:53,name:'East Timorese'},
	{value:54,name:'Ecuadorean'},
	{value:55,name:'Egyptian'},
	{value:56,name:'Emirian'},
	{value:57,name:'Equatorial Guinean'},
	{value:58,name:'Eritrean'},
	{value:59,name:'Estonian'},
	{value:60,name:'Ethiopian'},
	{value:61,name:'Fijian'},
	{value:62,name:'Filipino'},
	{value:63,name:'Finnish'},
	{value:64,name:'French'},
	{value:65,name:'Gabonese'},
	{value:66,name:'Gambian'},
	{value:67,name:'Georgian'},
	{value:68,name:'German'},
	{value:69,name:'Ghanaian'},
	{value:70,name:'Greek'},
	{value:71,name:'Grenadian'},
	{value:72,name:'Guatemalan'},
	{value:73,name:'Guinea-Bissauan'},
	{value:74,name:'Guinean'},
	{value:75,name:'Guyanese'},
	{value:76,name:'Haitian'},
	{value:77,name:'Herzegovinian'},
	{value:78,name:'Honduran'},
	{value:79,name:'Hungarian'},
	{value:80,name:'I-Kiribati'},
	{value:81,name:'Icelander'},
	{value:82,name:'Indian'},
	{value:83,name:'Indonesian'},
	{value:84,name:'Iranian'},
	{value:85,name:'Iraqi'},
	{value:86,name:'Irish'},
	{value:87,name:'Israeli'},
	{value:88,name:'Italian'},
	{value:89,name:'Ivorian'},
	{value:90,name:'Jamaican'},
	{value:91,name:'Japanese'},
	{value:92,name:'Jordanian'},
	{value:93,name:'Kazakhstani'},
	{value:94,name:'Kenyan'},
	{value:95,name:'Kittian and Nevisian'},
	{value:96,name:'Kuwaiti'},
	{value:97,name:'Kyrgyz'},
	{value:98,name:'Laotian'},
	{value:99,name:'Latvian'},
	{value:100,name:'Lebanese'},
	{value:101,name:'Liberian'},
	{value:102,name:'Libyan'},
	{value:103,name:'Liechtensteiner'},
	{value:104,name:'Lithuanian'},
	{value:105,name:'Luxembourger'},
	{value:106,name:'Macedonian'},
	{value:107,name:'Malagasy'},
	{value:108,name:'Malawian'},
	{value:109,name:'Malaysian'},
	{value:110,name:'Maldivan'},
	{value:111,name:'Malian'},
	{value:112,name:'Maltese'},
	{value:113,name:'Marshallese'},
	{value:114,name:'Mauritanian'},
	{value:115,name:'Mauritian'},
	{value:116,name:'Mexican'},
	{value:117,name:'Micronesian'},
	{value:118,name:'Moldovan'},
	{value:119,name:'Monacan'},
	{value:120,name:'Mongolian'},
	{value:121,name:'Moroccan'},
	{value:122,name:'Mosotho'},
	{value:123,name:'Motswana'},
	{value:124,name:'Mozambican'},
	{value:125,name:'Namibian'},
	{value:126,name:'Nauruan'},
	{value:127,name:'Nepalese'},
	{value:128,name:'New Zealander'},
	{value:129,name:'Nicaraguan'},
	{value:130,name:'Nigerian'},
	{value:131,name:'Nigerien'},
	{value:132,name:'North Korean'},
	{value:133,name:'Northern Irish'},
	{value:134,name:'Norwegian'},
	{value:135,name:'Omani'},
	{value:136,name:'Pakistani'},
	{value:137,name:'Palauan'},
	{value:138,name:'Panamanian'},
	{value:139,name:'Papua New Guinean'},
	{value:140,name:'Paraguayan'},
	{value:141,name:'Peruvian'},
	{value:142,name:'Polish'},
	{value:143,name:'Portuguese'},
	{value:144,name:'Qatari'},
	{value:145,name:'Romanian'},
	{value:146,name:'Russian'},
	{value:147,name:'Rwandan'},
	{value:148,name:'Saint Lucian'},
	{value:149,name:'Salvadoran'},
	{value:150,name:'Samoan'},
	{value:151,name:'San Marinese'},
	{value:152,name:'Sao Tomean'},
	{value:153,name:'Saudi'},
	{value:154,name:'Scottish'},
	{value:155,name:'Senegalese'},
	{value:156,name:'Serbian'},
	{value:157,name:'Seychellois'},
	{value:158,name:'Sierra Leonean'},
	{value:159,name:'Singaporean'},
	{value:160,name:'Slovakian'},
	{value:161,name:'Slovenian'},
	{value:162,name:'Solomon Islander'},
	{value:163,name:'Somali'},
	{value:164,name:'South African'},
	{value:165,name:'South Korean'},
	{value:166,name:'Spanish'},
	{value:167,name:'Sri Lankan'},
	{value:168,name:'Sudanese'},
	{value:169,name:'Surinamer'},
	{value:170,name:'Swazi'},
	{value:171,name:'Swedish'},
	{value:172,name:'Swiss'},
	{value:173,name:'Syrian'},
	{value:174,name:'Taiwanese'},
	{value:175,name:'Tajik'},
	{value:176,name:'Tanzanian'},
	{value:177,name:'Thai'},
	{value:178,name:'Togolese'},
	{value:179,name:'Tongan'},
	{value:180,name:'Trinidadian or Tobagonian'},
	{value:181,name:'Tunisian'},
	{value:182,name:'Turkish'},
	{value:183,name:'Tuvaluan'},
	{value:184,name:'Ugandan'},
	{value:185,name:'Ukrainian'},
	{value:186,name:'Uruguayan'},
	{value:187,name:'Uzbekistani'},
	{value:188,name:'Venezuelan'},
	{value:189,name:'Vietnamese'},
	{value:190,name:'Welsh'},
	{value:191,name:'Yemenite'},
	{value:192,name:'Zambian'},
	{value:193,name:'Zimbabwean'}
]

