import keyMirror from 'react/lib/keyMirror';

export default {
    ADD_ROLE: 'ADD_ROLE',
    ADD_ROLE_SUCCESS:'ADD_ROLE_SUCCESS',
    ADD_ROLE_FAIL:'ADD_ROLE_FAIL',
    GET_ROLE:'GET_ROLE',
    REMOVE_ROLE:'REMOVE_ROLE',
    GET_ROLE_EDIT:'GET_ROLE_EDIT',
    GET_PERMISSION_JSON :'GET_PERMISSION_JSON'
};

