import keyMirror from 'react/lib/keyMirror';

export default {
	ADD_USER: 'ADD_USER',
	ADD_USER_SUCCESS:'ADD_USER_SUCCESS',
	GET_USERS_FAIL:'GET_USERS_FAIL',
	GET_USERS: 'GET_USERS',
	GET_USER_ID:'GET_USER_ID',
	EDIT_USER:'EDIT_USER',
	REMOVE_USER: 'REMOVE_USER',
	REMOVE_USER_FAIL: 'REMOVE_USER_FAIL',
	DISABLE_USER:'DISABLE_USER',
	LOGIN_USER: 'LOGIN_USER',
	LOGOUT_USER: 'LOGOUT_USER',
    GET_A_USER: 'GET_A_USER',
	SEND_MAIL : 'SEND_MAIL',
	CHECK_TOKEN :'CHECK_TOKEN',
	CHANGE_PASS : 'CHANGE_PASS',
    GET_USER_NAME:'GET_USER_NAME',
    AUTH_GG : 'AUTH_GG'
};

